
# tap repositories and their packages

tap homebrew/core
brew coreutils
brew gdbm
brew gettext
brew go
brew jemalloc
brew libffi
brew libidn2
brew libtermkey
brew libunistring
brew libuv
brew libvterm
brew libyaml
brew llvm
brew luajit
brew mas
brew mplayer
brew msgpack
brew neovim
brew openssl
brew p7zip
brew perl
brew python
brew readline
brew ruby
brew sourcekitten
brew sqlite
brew terminal-notifier
brew unibilium
brew vim
brew wakeonlan
brew wget
brew xz

tap homebrew/bundle

tap homebrew/cask-drivers

tap homebrew/cask-fonts

tap homebrew/cask
cask atom
cask coconutbattery
cask dropbox
cask google-chrome
cask iterm2
cask minecraft

tap rcmdnk/file
brew brew-file

# Other Cask applications
cask cheatsheet
cask discord
cask gimp
cask google-drive-file-stream
cask java
cask signal

# App Store applications
appstore 682658836 GarageBand (10.3.1)
appstore 408981434 iMovie (10.1.9)
appstore 409183694 Keynote (8.2)
appstore 539883307 LINE (5.10.1)
appstore 409203825 Numbers (5.2)
appstore 409201541 Pages (7.2)
appstore 497799835 Xcode (10.0)
