" let g:ale_sign_column_always = 1
set signcolumn=yes
highlight SignColumn ctermbg=15
highlight SignColumn ctermfg=15
highlight SignColumn guisp=15
highlight SignColumn guifg=15
highlight SignColumn guibg=15
let g:ale_sign_error = '☠️'
let g:ale_sign_warning = '⚠️'
